ci: update node version
Use new LTS version of node at Travis-CI build

REF #727

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,6 @@
 language: node_js
 node_js:
-  - "8"
+  - "10"
 
 branches:
   only:
@@ -19,20 +19,20 @@ script:
 after_success:
   - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
   - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
-      echo "deploy for upstream master merge";
-      cd ./functions;
-      pwd;
-      npm install;
-      npm install -g firebase-tools;
-      bash ../scripts/firebase-deploy.sh;
-      if [ "$?" != 0 ]; then
-        echo "ERROR with deployment";
-        return 1;
-      else
-        echo "======deployment done======";
-      fi
+    echo "deploy for upstream master merge";
+    cd ./functions;
+    pwd;
+    npm install;
+    npm install -g firebase-tools;
+    bash ../scripts/firebase-deploy.sh;
+    if [ "$?" != 0 ]; then
+    echo "ERROR with deployment";
+    return 1;
     else
-      echo "Pull Request only build and test";
-      bash ./scripts/firebase-deploy.sh --dry-run
-      exit;
+    echo "======deployment done======";
+    fi
+    else
+    echo "Pull Request only build and test";
+    bash ./scripts/firebase-deploy.sh --dry-run
+    exit;
     fi
